[package]
name = "rust-graphql-example"
version = "0.1.0"
authors = ["Jordan Shaw <jordanshaw86@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4"
diesel = "1"
juniper = "0.14"
juniper-from-schema = "0.5"
juniper_rocket = "0.5"
serde_json = "1"
dotenv = "0.15"
juniper-eager-loading = "0.5"

[dev-dependencies]
assert-json-diff = "1"
diesel-factories = "1"
