CREATE TABLE IF NOT EXISTS todo_lists 
(
    id   BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name TEXT    NOT NULL,
    text TEXT    NOT NULL,
    done BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS items 
(
    id   BIGINT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    todo_list_id BIGINT UNSIGNED NOT NULL,
    name TEXT    NOT NULL,
    due_date DATETIME NOT NULL,
    UNIQUE KEY todo_list_fk (todo_list_id)
);
